steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'me-west1-docker.pkg.dev/$PROJECT_ID/asrafmeat/website', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'me-west1-docker.pkg.dev/$PROJECT_ID/asrafmeat/website']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'asrafmeat'
      - '--image'
      - 'me-west1-docker.pkg.dev/$PROJECT_ID/asrafmeat/website'
      - '--region'
      - 'me-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'me-west1-docker.pkg.dev/$PROJECT_ID/asrafmeat/website'
